# Defining reusable workflow
name: AWS

# Trigger
on:
  workflow_call:
    inputs:
      SERVICE_NAME:
        required: true
        type: string
      CLUSTER_NAME:
        required: false
        type: string
        default: "GBADs-Dashboards-Cluster"
      AWS_REGION:
        required: false
        type: string
        default: "us-east-2"
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
        

# Workflow to restart AWS services
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Commit SHA
        id: commit-hash
        run: echo "::set-output name=sha7::$(echo ${GITHUB_SHA} | cut -c1-7)"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.AWS_REGION }}

      - name: Redeploy Amazon ECS service
        run: |
          existing_image_tag=$(aws ecs describe-task-definition --task-definition $existing_image --query 'taskDefinition.containerDefinitions[0].image' --output text)
          echo "TESTIMAGE: $existing_image_tag"
          aws ecs update-service --cluster ${{ inputs.CLUSTER_NAME }} --service ${{ inputs.SERVICE_NAME }} --force-new-deployment
