# Defining reusable workflow
name: Docker Build and Push

# Trigger
on:
  workflow_call:
    inputs:
      IMAGE_NAME:
        required: true
        type: string
      TAG:
        required: false
        type: string
        default: "latest"
      CONTEXT:
        required: false
        type: string
        default: "."
      DOCKERFILE:
        required: false
        type: string
        default: "./Dockerfile"
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
        

# Workflow to build and push docker containers
jobs:
  build_and_push:
    name: Build & Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ${{ inputs.CONTEXT }}
          file: ${{ inputs.DOCKERFILE }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.IMAGE_NAME }}:${{ inputs.TAG }}
